config/routes.rb
T2kuPragmatic::Application.routes.draw do

  constraints(Subdomain){match '/'=>'tasks#new'}
  
  devise_for :users,:controllers => { :registrations => "registrations" },:path => 'd' do
    get "/register", :to => "registrations#new",as:'register'
    get "/login", :to => "devise/sessions#new",as:'login'
    get '/logout', :to => "devise/sessions#destroy", as:'logout'
  end
  
  resources :users
  resources :tasks
  resources :books do
    resources :items
  end
  resources :definitions
  resources :theorems
  resources :problems
  resources :references
  resources :authors
  resources :robots
  resources :helps
  get 'account' => 'account#index',:as=>'account'
  get 'downloads' => 'home#downloads',:as=>'downloads'
  get 'about' => 'home#about',:as=>'about'

  root :to => 'home#index'  
  post '/ajax/create_user' => 'ajax#create_user'
  post '/ajax/save_new_task_description' => 'ajax#save_new_task_description'
  

end

app/models/definition.rb
class Definition
  include Mongoid::Document
end

app/controllers/definitions_controller.rb
# -*- encoding : utf-8 -*-
class DefinitionsController < InheritedResources::Base
  layout 'dtp'
  before_filter{
    @objects = Definition.all
  }
end

app/views/definitions/_form.html.erb
<style type="text/css" media="screen">
.CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}
.activeline {background: #f0fcff !important;}
.CodeMirror-scroll {
  font-size:18px;
  line-height:24px;
}
label{
  margin-right:20px;
}
input{
  display:inline-block;
}  
</style>

<%= form_for @definition do |f| %>
<p><label for="name">Thing to Define:</label><%= f.text_field :name %></p>
<p>Please type in the $\mathcal{F}$lora-$\mathcal{2}$ statements of this definition:</p>
  <%= f.text_area :code %>
<p>Please add some Ruby Matchers to this definition:</p>
  <%= f.text_area :regexp_code %>
  <%= f.submit 'Submit',style:'margin-top:10px'%>
<%end %>

<% content_for :butt do %>
  <%= javascript_include_tag 'code' %>
  <script type="text/javascript" charset="utf-8">
    var editor = CodeMirror.fromTextArea(document.getElementById("definition_code"), {
      mode: "prolog",
      lineNumbers: true
    });
    var editor2 = CodeMirror.fromTextArea(document.getElementById("definition_regexp_code"), {
      mode: "ruby",
      lineNumbers: true,
      theme:'rubyblue'
    });
  </script>
<%end %>

app/views/definitions/edit.html.erb
<h2>Edit Definition <a href="<%= definition_path(@definition) %>">#<%= @definition.id %></a></h2>

<%= render 'form' %>

app/views/definitions/index.html.erb
<h2>Welcome to the T2Ku Definitons browser</h2>

<p>To get started, click on a definition on the left, or <%= link_to 'add',new_definition_path %> a new one.</p>

app/views/definitions/new.html.erb
<h2>Add a Definition</h2>

<%= render 'form' %>

app/views/definitions/show.html.erb
<dd id="function" class="text absolute">
  <h1>#1 <%= @definition.name %> <span class="type"><%= link_to 'Edit',edit_definition_path(@definition) %></span> <span class="fav" id="$.each234"></span></h1>
  <p></p>
  <h2>Internals</h2>
  <h3>$\mathcal{F}$lora-$\mathcal{2}$ Statements</h3>
  <pre style="font-size:14px"><%= @definition.code %></pre>
  <h3>Ruby Matchers</h3>
  <pre id="regexp_code" class="cm-s-rubyblue" style="font-size:14px"><%= @definition.regexp_code %></pre>
  <h2>Descriptions</h2>
  <p>...</p>
</dd>

<% content_for :butt do %>
  <%= javascript_include_tag 'code' %>
  <script type="text/javascript" charset="utf-8">
      CodeMirror.runMode($("#regexp_code").text(), "ruby",
                         document.getElementById("regexp_code"));
  </script>
<%end %>