config/routes.rb
T2kuPragmatic::Application.routes.draw do

  constraints(Subdomain){match '/'=>'tasks#new'}
  
  devise_for :users,:controllers => { :registrations => "registrations" },:path => 'd' do
    get "/register", :to => "registrations#new",as:'register'
    get "/login", :to => "devise/sessions#new",as:'login'
    get '/logout', :to => "devise/sessions#destroy", as:'logout'
  end
  
  resources :users
  resources :tasks
  resources :books do
    resources :items
  end
  resources :definitions
  resources :theorems
  resources :problems
  resources :references
  resources :authors
  resources :robots
  resources :helps
  get 'account' => 'account#index',:as=>'account'
  get 'downloads' => 'home#downloads',:as=>'downloads'
  get 'about' => 'home#about',:as=>'about'

  root :to => 'home#index'  
  post '/ajax/create_user' => 'ajax#create_user'
  post '/ajax/save_new_task_description' => 'ajax#save_new_task_description'
  

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  include UrlHelper

  before_filter :set_locale,:view_no,:login_reg
  before_filter proc{
    # render text:headers and return
  }
  def set_locale
    I18n.locale = extract_locale_from_subdomain || I18n.default_locale
  end
  
  def view_no
    pos = "#{params[:controller]}_#{params[:action]}"
    @no = Hash.new
    if 'home_index'==pos
      @no[:headnav] = @no[:footer] = true
    end
    if params[:controller].to_s.start_with?('devise')
      @no[:footer] = true
    end
  end
    
  def login_reg
    if !user_signed_in?
      @new_user = User.new 
    end
  end
  
  def after_sign_in_path_for(resource_or_scope)
    if params[:redirect_to].blank?
      super(resource_or_scope)
    else
      params[:redirect_to]
    end
  end
  
  def render_optional_error_file(status_code)
    render :template => "/errors/#{status_code}.html.erb", :status => status_code, :layout => "application"
  end


  # Get locale code from request subdomain (like http://it.application.local:3000)
  # You have to put something like:
  # 127.0.0.1 en.t2ku.org.local
  # 127.0.0.1 zh.t2ku.org.local
  # in your /etc/hosts file to try this out locally
  def extract_locale_from_subdomain
    parsed_locale = request.subdomains.first
    parsed_locale = 'zh-CN' if 'zh'==parsed_locale
    return nil if nil==parsed_locale
    I18n.available_locales.include?(parsed_locale.to_sym) ? parsed_locale : nil
  end

end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-

module ApplicationHelper

  def err(resource)
    alert_or_notice(resource.errors.full_messages.join(",#{tt('and')}"),nil,{go_away:false}) if resource and !resource.errors.empty?
  end
  def avatar_url(user,s=80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?r=PG&s=#{s}"
  end

  def lize(str,condition=false)
    if condition
      "<li class=\"active\">#{str}</li>"
    else
      "<li>#{str}</li>"
    end
  end
  
  def clear
    '<br style="clear:both">'.html_safe
  end
  
  def clearer
    '<br style="clear:both">'.html_safe
  end


  def get_title
    ret = 'T2Ku'
    trans = I18n.t("t2ku.navigation_tab.#{params[:controller]}_#{params[:action]}",default:'not-found')
    trans = I18n.t("t2ku.navigation_tab.#{params[:controller]}",default:'not-found') if 'not-found'==trans
    ret += ' - '+trans unless 'not-found'==trans
    ret
  end
  def mathjax_config
    '<script type="text/x-mathjax-config">
  	    MathJax.Hub.Config({
  	     tex2jax: {
  	       inlineMath: [ ["$","$"] ],
  	       processEscapes: true
  	     }
  	    });
  	</script>'.html_safe
  end
  
  def language_switch
    cl='special'
    if I18n.locale.to_s=='en'
      link_to '中文',request.env['REQUEST_PATH']+'?locale=zh-CN',:class => cl
    else
      link_to 'English',request.env['REQUEST_PATH']+'?locale=en',:class => cl
    end
  end
  
  def tt(path)
    I18n.t('t2ku.'+path)
  end
  
  def title(page_title)
    content_for(:title) { page_title }
  end
  
  
  def pos_signature
    "#{params[:controller].parameterize}_#{params[:action].parameterize}"
  end
  
  def navigation_tab_root
    text = I18n.t("t2ku.navigation_tab_root")
    if "#{params[:controller].parameterize}_#{params[:action].parameterize}"=="tasks_new"
      "<span class=\"selected\">#{text}</span>".html_safe
    else
      link_to text,'/'
    end
  end
  
  def navigation_tab(controller=nil)
    current = true if controller.to_s == params[:controller]
    current = false if "#{params[:controller].parameterize}_#{params[:action].parameterize}"=="tasks_new"
    text = I18n.t("t2ku.navigation_tab.#{controller}")
    text = current_user.name if :account==controller and current_user
    if current
      "<span class=\"selected\">#{text}</span>".html_safe
    else
      link_to text,"/#{controller}"
    end
  end
  
  
  def alert_or_notice(alert = nil,notice = nil,options = {})
    ret = ''
    options[:style] ||= ''
    if alert or notice
      if notice
        notice+='.' unless notice.ends_with?('.') or notice.ends_with?('。') 
        simple = (notice==t('devise.sessions.signed_in') || notice==t('devise.sessions.signed_out'))
        if simple
          ret <<'<div class="alert_or_notice" style="'+options[:style]+'">
        			<div class="ui-widget anotice"  id="notice">
        				<div style="padding: 0pt 0.7em;" class="ui-state-highlight ui-corner-all"> 
        					<p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-info"></span>
        					<strong>'+tt('notice')+'</strong>: '+notice+'</p>
        				</div>
        			</div>
        			</div>
        			<script type="text/javascript" charset="utf-8">
                $(function() {
        	        setTimeout(function() {$(".alert_or_notice").hide(\'slide\',{direction:\'up\'},\'slow\')}, 2000 );
                });
              </script>'
        else
          ret <<'<div class="alert_or_notice" style="'+options[:style]+'">
    			<div class="ui-widget anotice"  id="notice">
    				<div style="padding: 0pt 0.7em;" class="ui-state-highlight ui-corner-all"> 
    					<p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-info"></span>
    					<strong style="line-height:18px">'+tt('notice')+'</strong>: </p><p style="padding-left:20px">'+notice+'</p>
    					<p style="text-align:right;padding-right:8px"><strong><a href="#" onclick="$(this).parent().parent().parent().parent().parent().hide(\'slide\',{direction:\'up\'},\'slow\')" class="special underline">Done</a></strong></p>
    				</div>
    			</div>
    			</div>'
		    end
      end
      if alert
        alert+='.' unless alert.ends_with?('.')
        ret <<'<div class="alert_or_notice" style="'+options[:style]+'">
  			<div class="ui-widget afailure" id="alert">
  				<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
  					<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
  					<strong>'+tt('failed')+':</strong> '+alert+'</p>
  				</div>
  			</div>
  			</div>'
      end
    end
    ret.html_safe
  end
  
  def under_development(height)
    return image_tag('under_construction.png',:style=>"height:#{height}px").html_safe
  end
end

app/views/application/_commonjs.html.erb
<%= javascript_include_tag 'application' %>
<script type="text/x-mathjax-config">
   MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ["$","$"] ],
      processEscapes: true
    }
   });
</script>
<script src="/MathJax/MathJax.js?config=TeX-AMS_HTML-full.js" type="text/javascript"></script>

app/views/application/_footer.html.erb
<p style="text-align:center" id="heroku-footer-p">
  
  
  &copy; 2011
  <a href="http://ofpsvr.org" target="_blank">Minqi Pan</a>,
  <a href="http://202.204.208.109/mathpage/" target="_blank">CNUniv</a>.
  Inspired by
  <a href="http://www.heroku.com/" target="_blank">Heroku</a>.

</p>

app/views/application/_headnav.erb
<div id="subheader" class="clearfix">
  <div class="app">
    <h1><%= link_to "T2Ku",root_path,id:"main_menu_link_general" %></h1>
  </div>

  <ul class="clearfix submenu">
		<%= navigation_array.join("\n").html_safe %>
  </ul>

</div>


<div id="innerright">
	<ul class="account-links inline">
	    <div style="display: block;" id="logged-in-links">
				<% if user_signed_in? %>
					<li><%= link_to image_tag(avatar_url(current_user,22),alt:'gravatar',style:'margin-top:-2px;border:1px solid #82859E;margin-right:2px;width:22px;height:22px'),current_user %><span style="position:relative;left: 8px;top:-7px;margin-right:6px"><%= link_to current_user.name,current_user %></span></li>
		      <li><%= link_to 'My Dashboard',account_path,id:'account_link',class:'special' %></li>
		      <li><%= link_to I18n.t('t2ku.navigation_special.logout'),destroy_user_session_path,:method=>:delete,id:"logout_link",class:'special' %></li>
				<% else %>
					<li><%= link_to I18n.t('t2ku.navigation_special.login'),new_user_session_path(redirect_to:request.path),id:"login_link",class:'special' %></li>
		      <li><%= link_to I18n.t('t2ku.navigation_special.reg'),new_user_registration_path,id:"reg_link",class:'special' %></li>
				<% end %>
	    </div>
  </ul>
</div>

app/views/application/_loginreg.html.erb
<div id="loginreg">

	<div id="login-form" class="floating_dialog" style="display:none">
		<%= form_tag new_user_session_path,:id=>'login_form',:style=>'margin-top:-14px' do %>
			<fieldset>
        <input type="hidden" name="redirect_to" value="<%= request.path %>"/>
				<label for="user_email">E-mail</label>
				<input type="text" class="text ui-widget-content ui-corner-all" value="" id="user_email_log" name="user[email]">
				<label for="user_password"><%= tt('loginreg.passwd') %></label>
				<input type="password" class="text ui-widget-content ui-corner-all" value="" id="user_password_log" name="user[password]" onkeypress="if(event.keyCode==13){$('#login_form').submit();}">
			</fieldset>
		<% end %>
	</div>

	<div id="reg-form" class="floating_dialog" style="display:none">
	  <div id="reg_display_when_success" style="display:none">
	    <div style="text-align:center;margin:21px 0">
	      <%= image_tag 'suc.png' %>
	    </div>
	    <p style="line-height: 22px;">
	      <%= tt('loginreg.reg_ok_msg').html_safe %>
	      <%=link_to tt('loginreg.resend_confirm'),new_user_confirmation_path%>
	    </p>
	  </div>
	  <div id="reg_normal_stuff">
      <div class="ui-widget afailure" id="error_reg" style="margin: 2px 0 22px 0;display:none">
        <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
          <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
          <strong><%= tt('error') %>:</strong> <span id="error_reg_content" style="line-height:18px"></span></p>
        </div>
      </div>
      <div id="spinningWheel_reg" style="display:none;margin-bottom:20px">
        <%= image_tag 'reg_ajax_wait.gif' %> Please wait ...
      </div>
  		<%= form_for @new_user,:url=>'/ajax/create_user',:remote=>true,:html=>{:id=>'reg_form',:style=>'margin-top:-10px'} do %>
  			<fieldset>
  			  <label for="user_name"><%= tt('loginreg.username') %></label>
  				<input type="text" class="text ui-widget-content ui-corner-all" value="" id="user_name" name="user[name]">
  				<label for="user_email">E-mail</label>
  				<input type="text" class="text ui-widget-content ui-corner-all" value="" id="user_email" name="user[email]">
  				<label for="user_password"><%= tt('loginreg.passwd') %></label>
  				<input type="password" class="text ui-widget-content ui-corner-all" value="" id="user_password" name="user[password]">
  				<label for="user_password_confirmation"><%= tt('loginreg.passwd_confirm') %></label>
  			  <input type="password" class="text ui-widget-content ui-corner-all" value="" id="user_password_confirmation" name="user[password_confirmation]">
  			</fieldset>
  		<% end %>
  	</div>
	</div>

</div>
<% content_for :butt do %>
<script type="text/javascript" charset="utf-8">
  jQuery(function() {
    var buttons1, buttons2;
    buttons1 = {};
    buttons1[I18n.t('t2ku.loginreg.button11')] = function() {
      return $("#login_form").submit();
    };
    buttons1[I18n.t('t2ku.loginreg.button12')] = function() {
      return $(this).dialog("close");
    };
    buttons1[I18n.t('t2ku.loginreg.button13')] = function() {
      return window.location.href = $("#login_link").attr('href');
    };
    buttons2 = {};
    buttons2[I18n.t('t2ku.loginreg.button21')] = function() {
      return $('#reg_form').submit();
    };
    buttons2[I18n.t('t2ku.loginreg.button22')] = function() {
      return $(this).dialog("close");
    };
    buttons2[I18n.t('t2ku.loginreg.button23')] = function() {
      return window.location.href = $("#reg_link").attr('href');
    };
    $("#login-form").dialog({
      title: I18n.t('t2ku.loginreg.button11'),
      autoOpen: false,
      height: 220,
      width: 380,
      modal: true,
      buttons: buttons1
    });
    $('#reg-form').dialog({
      title: I18n.t('t2ku.loginreg.button21'),
      autoOpen: false,
      height: 330,
      width: 350,
      modal: true,
      buttons: buttons2
    });
    window.App_UsersNew = new T2Ku.Views.UsersNew({
      el: $('#reg-form')
    });
    $("#reg_link").click(function() {
      $("#reg-form").dialog("open");
      return false;
    });
    return $("#login_link").click(function() {
      $("#login-form").dialog("open");
      return false;
    });
  });
</script>
<%end %>

app/views/application/_sys_menu.erb
<li><%= link_to 'Mission Launch',root_path %></li>
<li><%= link_to 'Tasks on Queue',tasks_path %></li>
<li><%= link_to 'T2Ku Books',books_path %></li>
<li><%= link_to 'Definitions',definitions_path %> / <%= link_to 'Theorems',theorems_path %> / <%= link_to 'Problems',problems_path %></li>
<li><%= link_to 'Robots',robots_path %></li>
<li><%= link_to 'Help',helps_path %></li>