config/routes.rb
T2kuPragmatic::Application.routes.draw do

  constraints(Subdomain){match '/'=>'tasks#new'}
  
  devise_for :users,:controllers => { :registrations => "registrations" },:path => 'd' do
    get "/register", :to => "registrations#new",as:'register'
    get "/login", :to => "devise/sessions#new",as:'login'
    get '/logout', :to => "devise/sessions#destroy", as:'logout'
  end
  
  resources :users
  resources :tasks
  resources :books do
    resources :items
  end
  resources :definitions
  resources :theorems
  resources :problems
  resources :references
  resources :authors
  resources :robots
  resources :helps
  get 'account' => 'account#index',:as=>'account'
  get 'downloads' => 'home#downloads',:as=>'downloads'
  get 'about' => 'home#about',:as=>'about'

  root :to => 'home#index'  
  post '/ajax/create_user' => 'ajax#create_user'
  post '/ajax/save_new_task_description' => 'ajax#save_new_task_description'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= get_title %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/favicon.ico" type="image/x-icon" />  
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <%= stylesheet_link_tag    "pre_application" %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag    "pre_application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>" id="<%= pos_signature %>">
	<header>
	  <%= render 'headnav' %>
	  <% if !user_signed_in? %>
      <%=render 'loginreg' %>
    <% else %>
      <% content_for :butt do %>

        <script type="text/javascript" charset="utf-8">
          jQuery(function() {
            T2Ku.current_user = new T2Ku.Models.User;
            T2Ku.current_user.set(<%=raw current_user.basic_attributes.to_json%>);
          });
        </script>

      <% end %>
    <% end %>
	  <%= alert_or_notice(flash[:alert],flash[:notice]) %>
	</header>
	
  <%= yield %>
	
  <footer>
	  <%= render 'footer'%>
  </footer>
  
  
  <%= render 'commonjs' %>
  <%= yield :butt %>
  <script type="text/javascript" charset="utf-8">
     jQuery(function(){
      <%= yield :butt2 %>
     })
  </script>
  
</body>
</html>

app/views/layouts/bookview.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= @book.title %> - T2Ku</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <!-- CSS: implied media=all -->
  <!-- CSS concatenated and minified via ant build script-->
  <%= stylesheet_link_tag "pre_application" %>
  <%= stylesheet_link_tag 'bookview' %>
  <!-- end CSS-->
  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except for Modernizr / Respond.
       Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
       For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag    "pre_application" %>
</head>
<body>


  <header>
	  <%= render 'headnav' %>
	  <%= render 'loginreg' if !user_signed_in? %>
	  <%= alert_or_notice(flash[:alert],flash[:notice]) %>
	</header>

  <div class="document">
    <div class="documentwrapper">
      <div class="bodywrapper">
        <div class="body">
          <%= yield %>
        </div><!-- div.body -->
      </div>
    </div>
    <div class="sphinxsidebar">

      <div class="sphinxsidebarwrapper">
          <h3><%= link_to @book.title,@book %></h3>
          <ul id="sidetoc">
<%@book.items.pageitems.topitems.rank.each do |item| %>
<li><%=link_to item.name,book_item_path(@book,item),:class=>( (!@item.blank? and @item.name==item.name) ? 'selected' : '' ) %></li>
<% if item.children.count > 0 %>
  <ul>
    <% item.children.each do |child| %>
      <li><%=link_to child.name,book_item_path(@book,child) %></li>
    <% end %>
  </ul>
<% end %>
<%end %>

</ul>
<%if @item%>

          <h4>Previous page</h4>
          <p class="topless">
            <%if @item.prev%>
              <%=link_to @item.prev.name,book_item_path(@book,@item.prev),title:@item.prev.name%>
            <%else%>
              <%=link_to @book.title,book_path(@book),title:@book.title%>
            <%end%>
          </p>
          <h4>Next page</h4>
          <p class="topless">
            <%if @item.next%>
              <%=link_to @item.next.name,book_item_path(@book,@item.next),title:@item.next.name%>
            <%else%>
              <%=link_to 'New Page',new_book_item_path(@book),title:"New Page"%>
            <%end%>
          </p>
<h3>This Page</h3>
<ul class="this-page-menu">
<li>
    <%= link_to 'Edit',edit_book_item_path(@book,@item) %>
</li>

<li><a href="../_sources/whatsnew/2.7.txt"
       rel="nofollow">Show Source</a></li>
</ul>
<%else%>

<h4>Previous page</h4>
<p class="topless">
  <%=link_to @book.title,book_path(@book),title:@book.title%>
</p>
<h4>Next page</h4>
<p class="topless">
  <%=link_to @book.firstpage.name,book_item_path(@book,@book.firstpage),title:@book.firstpage.name%>
</p>
<h3>This page</h3>
<ul class="this-page-menu">
<li>
    <%= link_to 'Edit this Book',edit_book_path(@book) %>
</li>

</ul>
<%end%>

        <div id="searchbox" style="">
          <h3>Quick search</h3>
            <form class="search" action="../search.html" method="get">
              <input type="text" name="q" size="18" />
              <input type="submit" value="Go" />
              <input type="hidden" name="check_keywords" value="yes" />

              <input type="hidden" name="area" value="default" />
            </form>
            <p class="searchtip" style="font-size: 90%">
            Enter search terms or a module, class or function name.
            </p>
        </div>

      </div>
    </div>

    <div class="clearer"></div>
  </div>
  <div class="related">
    <h3>Navigation</h3>
    <ul>
    <%if @item%>
      <li class="right" >
        <%if @item.next%>
          <%=link_to 'next',book_item_path(@book,@item.next),title:@item.next.name%> |
        <%else%>
          <%=link_to 'new page',new_book_item_path(@book),title:"New Page"%> |
        <%end%>
      </li>
      <li class="right" >
        <%if @item.father%>
          <%=link_to 'up',book_item_path(@book,@item.father),title:@item.father.name%> |
        <%else%>
          <%=link_to 'up',book_path(@book),title:@book.title%> |
        <%end%>
      </li>
      <li class="right" >
        <%=link_to 'index',books_path,title:'Books'%> |
      </li>
      <li class="right" >
        <%if @item.prev%>
          <%=link_to 'prev',book_item_path(@book,@item.prev),title:@item.prev.name%> |
        <%else%>
          <%=link_to 'prev',book_path(@book),title:@book.title%> |
        <%end%>
      </li>
    <%else%>
      <li class="right" >
        <%=link_to 'next',book_item_path(@book,@book.firstpage),title:@book.firstpage.name%> |
      </li>
      <li class="right" >
          <%=link_to 'up',books_path,title:'Books'%> |
      </li>
      <li class="right" >
        <%=link_to 'index',book_path(@book),title:@book.title%> |
      </li>
      <li class="right" >
        <%=link_to 'prev',book_path(@book),title:@book.title%> |
      </li>
    <%end%>
      
      <li><img src="/icons/book_open.png" alt=""
               style="vertical-align: middle; margin-top: -1px"/></li>
      <li><%= link_to @book.title,@book %> &raquo;</li>
<% if @page %>
      <li> <%= @page.name %></li> 
<% elsif 'pages_index'==pos_signature %>
      <li> <%= link_to 'All Pages',book_items_path(@book) %></li> 
<% elsif 'books_show'==pos_signature %>
      <li> <%= link_to 'Frontpage',@book %></li> 
<% end %>
    </ul>
  </div>
  <div class="footer">

  <br />
  Book Copyright Belongs to the Original Author(s)<br />
  
  
  &copy; 2011
  <a href="http://ofpsvr.org" target="_blank">Minqi Pan</a>,
  <a href="http://202.204.208.109/mathpage/" target="_blank">CNUniv</a>.
  Inspired by
  <a href="http://docs.python.org/" target="_blank">Python DocBrowser</a>.
  </div>


<!-- JavaScript at the bottom for fast page loading -->
<%= render 'commonjs' %>
<%= javascript_include_tag 'bookview' %>
<%= yield :butt %>
<script type="text/javascript" charset="utf-8">
  if($('.sphinxsidebar').height() > $('div.body').height()){
    $('div.body').height($('.sphinxsidebar').height());
  }
</script>
</body>  


</html>

app/views/layouts/dtp.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>T2Ku <%= controller.controller_name %> Browser</title>
  <%= stylesheet_link_tag "pre_application" %>
  <%= stylesheet_link_tag    "dtp" %>
  <%= javascript_include_tag    "pre_application" %>
</head>
<body id="page">
  
  <header>
	  <%= render 'headnav' %>
	  <%= render 'loginreg' if !user_signed_in? %>
	  <%= alert_or_notice(flash[:alert],flash[:notice]) %>
	</header>

  <div id="body">
    <div id="browser">
        <div class="inner">
              <p class="loading"><%= image_tag 'icons/add.png' %> <%= link_to 'Add a Definition',new_definition_path,style:'color:white' %></p>
<dl id="categories">
  <% @objects.each do |item| %>
  <dt id="0" onclick="window.location.href='<%=j definition_path(item) %>'">#<%= item.id %>. <%= item.name %></dt>
  <%end %>
</dl>

        </div>
    </div>
    <div id="detail">
        <div class="inner">
          <%= yield %>
        </div>
    </div>
  </div>
  <p id="credit"><a href="http://api.jquery.com/browser/">Inspired by jQuery API-Browser</a></p>

  <%= render 'commonjs' %>
  <%= javascript_include_tag "dtp" %>
  <%= yield :butt %>
</body>
</html>